apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-postgres"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-postgres"
  serviceName: "{{ .Release.Name }}-postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-postgres"
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.db.repository }}:{{ .Values.db.tag }}"
          imagePullPolicy: "{{ .Values.db.imagepullPolicy }}"
          ports:
            - containerPort: {{ .Values.db.port }}
              name: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.existingSecrets.dbsecretName }}"
                  key: POSTGRES_DB
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U careerpath -d careerpath
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "{{ .Values.db.volumeClaimTemplates.storageClassName }}"
        resources:
          requests:
            storage: {{ .Values.db.volumeClaimTemplates.resources.requests.storage | quote }}