apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migration-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec: 
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Release.Name }}-migration
    spec:
      restartPolicy: OnFailure
      {{- if .Values.imagePullSecrets.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}
      containers:
        - name: prisma-migrate
          image: "{{ .Values.migration.repository }}:{{ .Values.migration.tag }}"
          imagePullPolicy: {{ .Values.migration.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecrets.dbsecretName }}
                  key: DATABASE_URL