api:
  replicas: 2
  image: aminehamad/careerpath-api
  pullPolicy: IfNotPresent
  tag: "latest"
  service:
    type: ClusterIP
    port: 4000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  existingSecrets:
    dbsecretName: "db-secrets"
    appSecretName: "app-secrets"
configMapData:
    PORT: "4000"
    VITE_API_URL: http://localhost:4000/api