apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Release.Name }}-postgres"
  name: "{{ .Release.Name }}-postgres"
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: postgres
    port: {{ .Values.db.port }}
  selector:
    app: "{{ .Release.Name }}-postgres"
  clusterIP: None
